version: 2
updates:
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "osvalois"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "osvalois"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # Enable security updates for all ecosystems
  open-pull-requests-limit: 10
  
  # Group updates
  groups:
    docker-dependencies:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"