version: '3.8'
services:
  sonarqube:
    image: sonarqube-container-sonarqube:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - SONARQUBE_VERSION=${SONARQUBE_VERSION:-2025.1.0.77975}
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONARQUBE_VERSION=${SONARQUBE_VERSION:-2025.1.0.77975}
      - SONAR_WEB_CONTEXT=/
      - SONAR_WEB_HOST=0.0.0.0
      - SONAR_WEB_PORT=9000
      - SONAR_SECURITY_REALM=
      - SONAR_AUTHENTICATOR_DOWNCASE=false
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql_data: