---
services:
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        BUILD_VERSION: ${BUILD_VERSION:-2025.3}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
    image: sonarqube-devsecops:2025-latest
    container_name: sonarqube-2025
    restart: unless-stopped
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    env_file:
      - .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
      - sonarqube_reports:/opt/sonarqube/reports
    networks:
      - sonarqube-network
    deploy:
      resources:
        limits:
          cpus: '${DEPLOY_CPU_LIMIT:-4}'
          memory: ${DEPLOY_MEMORY_LIMIT:-8G}
        reservations:
          cpus: '${DEPLOY_CPU_RESERVATION:-2}'
          memory: ${DEPLOY_MEMORY_RESERVATION:-4G}

networks:
  sonarqube-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.20.0.0/16}

volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_temp:
    driver: local
  sonarqube_reports:
    driver: local
