---
services:
  sonarqube:
    image: sonarqube:25.5.0.107428-community
    container_name: sonarqube-working
    restart: unless-stopped
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    environment:
      # Use H2 embedded database (only for testing/development)
      - SONAR_EMBEDDEDDATABASE_PORT=9092
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      # Elasticsearch configuration
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
      - ./plugins:/opt/sonarqube/extensions/plugins
    networks:
      - sonarqube-network

networks:
  sonarqube-network:
    driver: bridge

volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_temp:
    driver: local