---
services:
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        BUILD_VERSION: ${BUILD_VERSION:-2025.3}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
    image: sonarqube-enhanced:latest
    container_name: sonarqube-2025-h2
    restart: unless-stopped
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    environment:
      # Use H2 embedded database (only for testing/development)
      - SONAR_EMBEDDEDDATABASE_PORT=9092
      # Elasticsearch configuration - Fix memory settings
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_SEARCH_JAVAOPTS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
      - SONAR_SEARCH_JAVA_ADDITIONAL_OPTS=-Des.enforce.bootstrap.checks=false -Des.discovery.type=single-node
      # Web and CE memory settings
      - SONAR_WEB_JAVAOPTS=-Xmx512m -Xms256m
      - SONAR_CE_JAVAOPTS=-Xmx512m -Xms256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
      - sonarqube_reports:/opt/sonarqube/reports
    networks:
      - sonarqube-network

networks:
  sonarqube-network:
    driver: bridge

volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_temp:
    driver: local
  sonarqube_reports:
    driver: local