---
version: '3.9'
services:
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        BUILD_VERSION: ${BUILD_VERSION:-2025.3}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
    image: sonarqube-devsecops:2025-latest
    container_name: sonarqube-2025
    restart: unless-stopped
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://ep-floral-bush-a5ns5s26-pooler.us-east-2.aws.neon.tech/shsonar?user=shsonar_owner&password=npg_3oPHcnhxz7er&sslmode=require
      - SONAR_JDBC_USERNAME=shsonar_owner
      - SONAR_JDBC_PASSWORD=npg_3oPHcnhxz7er
      - SONARQUBE_VERSION=${SONARQUBE_VERSION:-2025.3}
      - SONAR_WEB_CONTEXT=/
      - SONAR_WEB_HOST=0.0.0.0
      - SONAR_WEB_PORT=9000
      - SONAR_SECURITY_REALM=
      - SONAR_AUTHENTICATOR_DOWNCASE=false
      # Performance optimizations for 2025
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseContainerSupport
      # For production, set vm.max_map_count=262144 on the host system instead
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      # Security enhancements
      - SONAR_TELEMETRY_ENABLE=false
      - SONAR_UPDATECENTER_ACTIVATE=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonarqube-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

networks:
  sonarqube-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_temp:
    driver: local
