[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway-ultimate"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[env]
# Remove conflicting memory settings
# Let the wrapper scripts handle memory configuration internally