[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 1800
healthcheckInterval = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
rootDirectory = "."
startupTimeout = 1800

[env]
# Elasticsearch bootstrap configuration
SONAR_ES_BOOTSTRAP_CHECKS_DISABLE = "true"
ES_JAVA_OPTS = "-Xms256m -Xmx512m -XX:+UseSerialGC -Des.enforce.bootstrap.checks=false"
SONAR_SEARCH_JAVA_ADDITIONAL_OPTS = "-Des.enforce.bootstrap.checks=false"

# Java optimization
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=65.0"
JAVA_TOOL_OPTIONS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=65.0"

# JVM memory settings
SONAR_WEB_JAVAOPTS = "-Xmx512m -Xms256m -XX:+UseSerialGC"
SONAR_CE_JAVAOPTS = "-Xmx512m -Xms256m -XX:+UseSerialGC"
SONAR_SEARCH_JAVAOPTS = "-Xmx512m -Xms256m"

# Network settings
SONAR_WEB_PORT = "9000"
PORT = "9000"
SONAR_WEB_HOST = "0.0.0.0"
SONAR_WEB_CONTEXT = "/"

# Feature settings
SONAR_TELEMETRY_ENABLE = "false"
SONAR_UPDATECENTER_ACTIVATE = "false"
SONAR_CLUSTER_ENABLED = "false"
SONAR_LOG_LEVEL = "INFO"
SONAR_FORCEAUTHENTICATION = "false"

# Database settings
SONAR_JDBC_URL = "jdbc:postgresql://ep-floral-bush-a5ns5s26-pooler.us-east-2.aws.neon.tech/shsonar?user=shsonar_owner&password=npg_3oPHcnhxz7er&sslmode=require"
SONAR_JDBC_USERNAME = "shsonar_owner"
SONAR_JDBC_PASSWORD = "npg_3oPHcnhxz7er"