[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[env]
# Minimal environment variables - let wrapper scripts handle memory
SONAR_WEB_HOST = "0.0.0.0"
SONAR_TELEMETRY_ENABLE = "false"
SONAR_UPDATECENTER_ACTIVATE = "false"

# Database configuration from Railway
SONAR_JDBC_URL = "${DATABASE_URL}"