[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
SONAR_ES_BOOTSTRAP_CHECKS_DISABLE = "true"
RUN_AS_ROOT = "true"
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
SONAR_WEB_JAVAOPTS = "-Xmx2g -Xms1g -XX:+UseG1GC"
SONAR_CE_JAVAOPTS = "-Xmx2g -Xms512m -XX:+UseG1GC"
SONAR_SEARCH_JAVAOPTS = "-Xmx1g -Xms512m -XX:MaxDirectMemorySize=256m"
SONAR_TELEMETRY_ENABLE = "false"
SONAR_UPDATECENTER_ACTIVATE = "false"
SONAR_WEB_PORT = "8080"
PORT = "8080"
SONARQUBE_WEB_JVM_OPTS = "-Xmx2g -Xms1g"
SONARQUBE_CE_JVM_OPTS = "-Xmx2g -Xms512m"
SONARQUBE_SEARCH_JVM_OPTS = "-Xmx1g -Xms512m"
SONAR_JDBC_URL = "jdbc:postgresql://ep-floral-bush-a5ns5s26-pooler.us-east-2.aws.neon.tech/shsonar?user=shsonar_owner&password=npg_3oPHcnhxz7er&sslmode=require"
SONAR_JDBC_USERNAME = "shsonar_owner"
SONAR_JDBC_PASSWORD = "npg_3oPHcnhxz7er"