[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 300
restartPolicyType = "never"

[env]
SONAR_ES_BOOTSTRAP_CHECKS_DISABLE = "true"
RUN_AS_ROOT = "true"
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"