[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.patch"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
SONAR_WEB_HOST = "0.0.0.0"