[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway-fix"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[[services]]
name = "sonarqube"
memory = "512MB"

[env]
# Use Railway's PORT variable
PORT = "${PORT}"

# Force root execution
RUN_AS_ROOT = "true"

# Disable Elasticsearch checks completely
SONAR_ES_BOOTSTRAP_CHECKS_DISABLE = "true"

# JVM Settings - Conservative memory usage
JAVA_OPTS = "-Xmx384m -Xms128m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m"

# SonarQube specific JVM settings
SONAR_WEB_JAVAOPTS = "-Xmx384m -Xms128m"
SONAR_CE_JAVAOPTS = "-Xmx384m -Xms128m"
SONAR_SEARCH_JAVAOPTS = "-Xmx512m -Xms512m -XX:MaxDirectMemorySize=256m"

# Disable telemetry
SONAR_TELEMETRY_ENABLE = "false"
SONAR_UPDATECENTER_ACTIVATE = "false"

# Logging
SONAR_LOG_LEVEL = "INFO"

# Network
SONAR_WEB_HOST = "0.0.0.0"