[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/api/system/status"
healthcheckTimeout = 1800
healthcheckInterval = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
rootDirectory = "."
startupTimeout = 1800

[env]
# Elasticsearch bootstrap configuration
SONAR_ES_BOOTSTRAP_CHECKS_DISABLE = "true"
ES_JAVA_OPTS = "-Xms256m -Xmx512m -XX:MaxDirectMemorySize=256m -Des.enforce.bootstrap.checks=false -Des.bootstrap.system_call_filter=false -Des.bootstrap.checks=false -Des.node.store.allow_mmap=false"
SONAR_SEARCH_JAVA_ADDITIONAL_OPTS = "-Des.enforce.bootstrap.checks=false -Des.bootstrap.system_call_filter=false -Des.bootstrap.checks=false -Des.node.store.allow_mmap=false"

# Java optimization - reduced memory usage
JAVA_OPTS = "-XX:MaxRAMPercentage=50.0"
JAVA_TOOL_OPTIONS = "-XX:MaxRAMPercentage=50.0"

# JVM memory settings - reduced for Railway constraints
SONAR_WEB_JAVAOPTS = "-Xmx512m -Xms256m"
SONAR_CE_JAVAOPTS = "-Xmx512m -Xms256m"
SONAR_SEARCH_JAVAOPTS = "-Xms256m -Xmx512m -XX:MaxDirectMemorySize=256m -Des.enforce.bootstrap.checks=false -Des.bootstrap.system_call_filter=false -Des.bootstrap.checks=false -Des.node.store.allow_mmap=false"

# Network settings
SONAR_WEB_PORT = "9000"
PORT = "9000"
SONAR_WEB_HOST = "0.0.0.0"
SONAR_WEB_CONTEXT = "/"

# Feature settings
SONAR_TELEMETRY_ENABLE = "false"
SONAR_UPDATECENTER_ACTIVATE = "false"
SONAR_CLUSTER_ENABLED = "false"
SONAR_LOG_LEVEL = "INFO"
SONAR_FORCEAUTHENTICATION = "false"

# CNES Report Plugin configuration
SONAR_PDF_REPORT_ENABLED = "true"
SONAR_CNES_REPORT_EXPORTERS = "true"
SONAR_CNES_REPORT_CONFIDENTIAL = "false"

# Database settings
SONAR_JDBC_URL = "jdbc:postgresql://ep-floral-bush-a5ns5s26-pooler.us-east-2.aws.neon.tech/shsonar?user=shsonar_owner&password=npg_3oPHcnhxz7er&sslmode=require"
SONAR_JDBC_USERNAME = "shsonar_owner"
SONAR_JDBC_PASSWORD = "npg_3oPHcnhxz7er"